A FOREX EXPERT SYSTEM BASED ON RULE BASED EVIDENTIAL REASONING

Link: https://www.sciencedirect.com/science/article/pii/S0957417415008301

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/Ghaby-X/Algo_forex/main/EURUSD_D1.csv"
df = pd.read_csv(url)

In [2]:
df

      2007-06-04 00:00  1.34422  1.34978  1.34317  1.34907  658167
0     2007-06-05 00:00  1.34909  1.35515  1.34885  1.35157  662588
1     2007-06-06 00:00  1.35162  1.35371  1.34844  1.34957  663033
2     2007-06-07 00:00  1.34963  1.35113  1.34209  1.34247  659601
3     2007-06-08 00:00  1.34251  1.34269  1.33225  1.33708  599578
4     2007-06-10 00:00  1.33671  1.33711  1.33513  1.33559   56852
...                ...      ...      ...      ...      ...     ...
5006  2023-06-05 00:00  1.06970  1.07224  1.06744  1.07113  254750
5007  2023-06-06 00:00  1.07112  1.07328  1.06669  1.06984  241566
5008  2023-06-07 00:00  1.06985  1.07396  1.06682  1.07069  250359
5009  2023-06-08 00:00  1.07070  1.07869  1.07009  1.07818  255511
5010  2023-06-09 00:00  1.07819  1.07850  1.07746  1.07777   44525

[5011 rows x 6 columns]

The adapted moving average indicator dEMA

In [ ]:
def dEMA(bid, ask, EMA):
  p = (bid + ask)/2
  return p - EMA